---
title: "ASL vis"
author: "Abby Lewis"
date: "2/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ticks <- read_csv("../0_Data_files/ticks-targets.csv.gz")

sites <- unique(ticks$siteID)
#ticks = ticks_raw%>%
#  filter(!is.na(ambloyomma_americanum)|!is.na(ixodes_scapularis))

for (i in 1:length(sites)){
  current_site <- subset(ticks, siteID == sites[i])
  
  aa <- ggplot(data = current_site, aes(x = time, y = ambloyomma_americanum, color = plotID, fill = plotID))+
    geom_point(size = 2)+
    geom_line()+
    ggtitle("A. americanum")+
    facet_wrap(vars(Year), scales = "free_x")+
    theme_classic()
  print(aa)
  
  is <- ggplot(data = current_site, aes(x = time, y = ixodes_scapularis, color = plotID, fill = plotID))+
    geom_point(size = 2)+
    geom_line()+
    ggtitle("I. scapularis")+
    facet_wrap(vars(Year), scales = "free_x")+
    theme_classic()
  print(is)
}


#-- to add to Mary's file
sum = ticks%>%
  mutate(month = month(as.Date(time)))%>%
  group_by(plotID,Year,month)%>%
  summarize(A = sum(!is.na(ambloyomma_americanum))/n(),
            I = sum(!is.na(ambloyomma_americanum))/n())%>%
  mutate(date = as.Date(paste0(Year,"-",month,"-01")))

sum%>%
  ggplot(aes(x = date, y = plotID, fill = A*100))+
  geom_tile()+
  scale_fill_viridis_c(na.value = "black")+
  labs(fill = "Percent of Ambloyomma \namericanum data that is \nnot missing")+
  theme_classic()

sum%>%
  ggplot(aes(x = date, y = plotID, fill = A*100))+
  geom_tile()+
  scale_fill_viridis_c(na.value = "black")+
  labs(fill = "Percent of Ixodes \nscapularis data that \nis not missing")+
  theme_classic()

map = ticks%>%
  group_by(siteID)%>%
  summarize(lat = unique(decimalLatitude),
            long = unique(decimalLongitude))

MapData <- map_data("state")%>%
  fortify()

ggplot() +
  geom_map(data = MapData, map = MapData,
                  aes(map_id=region),
                  fill = "white", colour = "#7f7f7f", size=0.5)+
  geom_point(aes(x = long, y = lat, color = siteID),size = 3, data = map)+
  theme_bw() + xlab(NULL) + ylab(NULL) +
  theme(
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.ticks = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank())+
  guides(fill = F)
  #guides(fill = guide_legend(override.aes=list(shape=21)))

```


```{r}
sites <- c("KONZ", "ORNL", "SCBI", "TALL")
#ticks = ticks_raw%>%
#  filter(!is.na(ambloyomma_americanum)|!is.na(ixodes_scapularis))

for (i in 1:length(sites)){
  current_site <- subset(ticks, siteID == sites[i])
  
  max <- ggplot(data = current_site, aes(x = time, y = airTempMax_degC, color = plotID, fill = plotID))+
    geom_point(size = 2)+
    geom_line()+
    ggtitle("Max temp")+
    facet_wrap(vars(Year), scales = "free_x")+
    theme_classic()
  print(aa)
  
  min <- ggplot(data = current_site, aes(x = time, y = airTempMin_degC, color = plotID, fill = plotID))+
    geom_point(size = 2)+
    geom_line()+
    ggtitle("Min temp")+
    facet_wrap(vars(Year), scales = "free_x")+
    theme_classic()
  print(is)
}
```
