---
title: "1_Exploratory_visualization"
author: "Mary Lofton"
date: "2/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(root.dir = 'C:/Users/Mary Lofton/Documents/RProjects/VTicks') (switching this so it can more easily used on different computers. Not needed)
#install.packages('pacman')
pacman::p_load(tidyverse, lubridate)
```

## Visualize tick data


```{r, echo = FALSE}
ticks <- read_csv("../0_Data_files/ticks-targets.csv.gz")

sites <- unique(ticks$siteID)

for (i in 1:length(sites)){
  current_site <- subset(ticks, siteID == sites[i])
  
aa <- ggplot(data = current_site, aes(x = epiWeek, y = ambloyomma_americanum, color = plotID, fill = plotID))+
  geom_point(size = 2)+
  geom_line()+
  ggtitle("A. americanum")+
  facet_grid(vars(Year), scales = "free_x")+
  theme_bw()
print(aa)

is <- ggplot(data = current_site, aes(x = epiWeek, y = ixodes_scapularis, color = plotID, fill = plotID))+
  geom_point(size = 2)+
  geom_line()+
  ggtitle("I. scapularis")+
  facet_grid(vars(Year), scales = "free_x")+
  theme_bw()
print(is)

}
```

## Visualize environmental covariate data

You can also embed plots, for example:

```{r , echo=FALSE}
core_sites <- c("KONZ","ORNL","SCBI","TALL")

env_vars <- c("RHMin_precent","RHMax_precent","airTempMin_degC","airTempMax_degC")

for (i in 1:length(core_sites)){
  current_site <- subset(ticks, siteID == core_sites[i])
  
  for(j in 1:length(env_vars)){
  
plot_var <- ggplot(data = current_site, aes_string(x = "epiWeek", y = env_vars[j], color = 'plotID', fill = 'plotID'))+
  geom_point(size = 2)+
  geom_line()+
  ggtitle(env_vars[j])+
  facet_grid(vars(Year), scales = "free_x")+
  theme_bw()
print(plot_var)

}
}

#I made an edit
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
