



```{r}

library(agricolae)
library(tidybayes)
library(tidyverse)

ticks <- read_csv("../0_Data_files/ticks-targets.csv.gz")

```


Breaking down the data
```{r}
view(ticks)

aa_ticks<- ticks%>% select(ambloyomma_americanum, siteID, plotID)

is_ticks<- ticks%>% select(ixodes_scapularis, siteID, plotID)

```

ANOVA for aa_ticks
```{r}
aa_ticks<- aa_ticks %>% drop_na(ambloyomma_americanum)

str(aa_ticks)

aa_ticks$siteID<- factor(aa_ticks$siteID)

aa_ticks$plotID<- factor(aa_ticks$plotID)

str(aa_ticks)

mod1.lm<-lm(ambloyomma_americanum ~ siteID/plotID, data= aa_ticks)

mod1.av<-aov(mod1.lm)

summary(mod1.av)

tukey.test<-TukeyHSD(mod1.av)

tukey.test

summary(tukey.test)

res1<-residuals(mod1.av)

shapiro.test(res1)

summary.aov(mod1.av)

qqnorm(res1)

anova(mod1.av)

summary(mod1.av)


```

ANOVA for is_ticks data
```{r}

is_ticks<- is_ticks %>% drop_na(ixodes_scapularis)

str(is_ticks)

is_ticks$siteID<- factor(is_ticks$siteID)

is_ticks$plotID<- factor(is_ticks$plotID)

str(is_ticks)

mod1.lm<-lm(ixodes_scapularis ~ siteID * plotID, data= is_ticks)

mod1.av<-aov(mod1.lm)

summary(mod1.av)

tukey.test<-TukeyHSD(mod1.av)

tukey.test

plot(tukey.test)

summary(tukey.test)

res1<-residuals(mod1.av)

shapiro.test(res1)

summary.aov(mod1.av)

qqnorm(res1)

anova(mod1.av)

summary(mod1.av)

```

