---
title: "Bayesian_NIMBLE_Assignment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(nimble)
library(rjags)
library(lubridate)
library(tidybayes)
library(tidyverse)
```



Very much a work in progress
Made by ASL 16 Mar 2021

Load and format PRISM driver data (this should be moved out of this script eventually!)
```{r}
files = list.files("../0_Data_files/PRISM_data")
files = files[grepl("PRISM_ppt",files)]
full_site = sub(".+_", "",sub(".csv","",files))
site = sub("[0-9]+","",gsub("-","",full_site))
plot = sub("[A-Z]+","",full_site)
plot[site == "BLAN"] <- "005-012"
drivers = read.csv(paste0("../0_Data_files/PRISM_data/",files[1]), skip = 10)%>%
  mutate(Site = site[1],
         Plot = plot[1])%>%
  filter(is.na(Date))
for(i in 1:length(files)){
  new = read.csv(paste0("../0_Data_files/PRISM_data/",files[i]), skip = 10)%>%
    mutate(Site = site[i],
           Plot = gsub("-[0-9]+","",plot[i]))
  drivers = drivers%>%
    full_join(new)
  while(nchar(plot[i])>0){
    new = read.csv(paste0("../0_Data_files/PRISM_data/",files[i]), skip = 10)%>%
      mutate(Site = site[i],
             Plot = gsub("-[0-9]+","",plot[i]))
    drivers = drivers%>%
      full_join(new)
    plot[i] = sub("[0-9][0-9][0-9]-*","",plot[i])
  }
}
drivers$Plot[drivers$Site == "KONZ"]<- "025"
drivers$plotID <- paste0(drivers$Site,"_",drivers$Plot)
write.csv(drivers, "../0_Data_files/PRISM_data/combined_prism_drivers.csv")
```

First attempt at the nimble model for all sites. Currently sites are different groups in the hierarchical model. This takes a LONG time to run on my computer
```{r}
ticks <- read_csv("../0_Data_files/ticks-targets.csv.gz")
drivers <- read.csv("../0_Data_files/PRISM_data/combined_prism_drivers.csv")

#NOTE: this does not include all data right now! Only days with driver data available
data = drivers%>%
  rename(time = Date,
         siteID = Site)%>%
  mutate(time = as.Date(time))%>%
  left_join(ticks)

group_index = as.numeric(factor(data$siteID)) #Set group index (currently by site)

logistic <- nimbleCode({

  # Priors
  theta1_global ~ dnorm(0, sd = 1000)
  sd1_global ~ dnorm(0, sd = 1000)
  sd_data ~ dnorm(0, sd = 1000)
  
  for(j in 1:n_groups){ #Currently the model is entirely dependent on temperature
    p1[j] ~ dnorm(theta1_global, sd = sd1_global)
  }

  #Loop through data points
  for(i in 1:n){
      # Process model
      pred[i] <- p1[group[i]] * temp[i]
      # Data model
      y[i]  ~ dnorm(pred[i], sd = sd_data)
  }

})

constants <- list(n = length(data$time),
                  n_groups = length(unique(group_index)),
                  group = group_index)

data <- list(temp = data$tmean..degrees.C.,
             y = data$ixodes_scapularis) #y = data$ambloyomma_americanum

nchain <- 3
inits <- list()
for(i in 1:nchain){
  inits[[i]] <- list(theta1_global = rnorm(1, 1, 1),
                     sd1_global = rnorm(1, 1, 1),
                     sd_data = rnorm(1, 1, 1))
}

nimble.out <- nimbleMCMC(code = logistic,
                           data = data,
                           inits = inits,
                           constants = constants,
                           monitors = c("theta1_global", "sd1_global", "sd_data"),
                           niter = 10000,
                           nchains = 3,
                           samplesAsCodaMCMC = TRUE)

plot(nimble.out) #sd_data does not converge
gelman.diag(nimble.out)  ## determine convergence. This is not running right now?

#Haven't gotten to this point yet
burnin <- 1000                               
nimble.burn <- window(nimble.out, start=burnin)

plot(nimble.burn) #
effectiveSize(nimble.burn)
gelman.diag(nimble.burn)  ## determine convergence

chain <- nimble.burn %>%
  tidybayes::spread_draws(theta1, theta2, theta4, sd_data)

pred_function <- function(p1, temp, group_i){
  p1[group_i] * temp[i]
}
```



Added by Sarah 22 Mar 21:
```{r}
###Goals this week : find reliable priors and dynamic model to mess with in the nimble framework. You gotta represent a couple of different sites with different populations. Historically some of the sites have had zero count and some have had a far number. Try to figure out 


unique(ticks$siteID)


ticks%>% filter(siteID == "TALL") %>% ggplot(aes(x= epiWeek, y= ixodes_scapularis, color= plotID))+
  geom_point()

ticks%>% filter(siteID == "TALL") %>% ggplot(aes(x= epiWeek, y= ambloyomma_americanum, color= plotID))+
  geom_point()

ticks_drivers<- full_join(ticks, drivers, by= "plotID")


ticks_drivers %>% filter(siteID == "TALL") %>% ggplot(aes(x=  ambloyomma_americanum, y= tmean..degrees.C., color= plotID))+
  geom_point()

```

